Feature: check bluetooth permissions
dronetag/flutter-opendroneid pull request #11
Opened 2022-12-30 12:00 UTC by matejglejtek

2023-01-16 12:24 UTC, marianhlavac commented
Jaký je pls progress na review?

2023-01-18 12:23 UTC, matejglejtek commented
Predelal jsem to dle domluvy, pouze se kontroluje status permissions bez requestu.

2023-01-19 11:35 UTC, albertmoravec requested changes
Super, preklopim tuhle logiku do Haralda a snad to bude fungovat lepe nez ted. Jedine co bych zmenil je ten throw, melo by to byt funkcne ekvivalentni.

EDIT: jeste jsem si uvedomil ze by bylo lepsi vracet nejakou specifictejsi exception

2023-01-19 11:35 UTC, albertmoravec commented on lib/flutter_opendroneid.dart
> +        return Future.error('Permissions not granted');
Pouzil bych klasicky `throw`, kdyz je to uvnitr `async` metody.

```suggestion
        throw Exception('Permissions not granted');
```

2023-01-19 11:35 UTC, albertmoravec commented on lib/flutter_opendroneid.dart
> +        return Future.error('Permissions not granted');
Stejne tady.

```suggestion
        throw Exception('Permissions not granted');
```

2023-01-19 11:46 UTC, albertmoravec commented on lib/flutter_opendroneid.dart
> +  static Future<bool> _ensureBluetoothPermissions() async {
Tim, ze se to jmenuje `ensure` bych se asi nebal thrownout tu `PermissionMissingException` rovnou tady a budes mit jednodussi posilani tech chybejicich permission.

Nicmene necham to na tobe.

2023-01-23 15:01 UTC, matejglejtek commented
Pokud nejaky chybi permission, vyhodi se MissingPermissionException s popisem, ktery permission chybi.

2023-01-25 10:24 UTC, marianhlavac commented
Na zaklade [diskuze na Slacku](https://getdronetag.slack.com/archives/CSPGWGPB6/p1674641327071239) to ted po Matejovi prevezmu a udelam nasledujici zmeny:

- Prejmenuji metodu `ensure` -> `assert` aby nazev nebyl zavadejici
- Prepisu logiku aby funkce v exception nevracela jen tu jednu chybejici permission ale seznam vsech ktery schazeji

To stejne provedu v https://github.com/dronetag/harald/pull/52

2023-01-25 11:50 UTC, marianhlavac commented
@albertmoravec @matejglejtek Pls nekdo o rychly review, pokud ok, pak to mergnu a preklopim to stejne do https://github.com/dronetag/harald/pull/52 .

2023-01-25 11:50 UTC, marianhlavac approved these changes

2023-01-25 12:31 UTC, matejglejtek commented
za mne ok

2023-01-25 15:41 UTC, merged